# information (endpoint /info)
info:
  app:
    name: Java Parameters
    version: ${project.version}
  java:
    version: ${java.version}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
      springframework:
        web: DEBUG
        data: DEBUG
        security: DEBUG
    com:
      javaparams: DEBUG

management:
  health:
    db:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - mappings

# Database

spring:
  datasource:
    url: jdbc:h2:file:./javaparams
    username: sa
    password:
  h2:
    console:
      enable: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  thymeleaf:
    cache: false
  security:
   oauth2:
     client:
       registration:
         github:
           clientId: ${GITHUB_CLIENT_ID}
           clientSecret: ${GITHUB_CLIENT_SECRET}
           scope:
             - read:user
           redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
       provider:
         github:
           authorization-uri: https://github.com/login/oauth/authorize
           token-uri: https://github.com/login/oauth/access_token
           user-info-uri: https://api.github.com/user

# Spring DOC
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: false
    use-root-path: false
  show-actuator: false

# security
security:
  enabled: false

# default server port
server:
  port: 8080
